component: scf
name: ap-guangzhou_default_kafka_to_cos_consumer
org: app
app: kafka_to_cos_consumer
stage: dev
inputs:
  name: kafka_to_cos_consumer
  src: ./
  description: CKAFKA data backup to COS. CKAFKA数据备份到COS
  handler: kafka_to_cos_consumer.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 300
  events:
    - ckafka: # ckafka触发器
        name: # input Ckafka  trigger name
        parameters:
          name: # input Ckafka Instance id        
          topic: # input Ckafka Topic name  
          maxMsgNum: 100
          offset: latest
          enable: true
