component: scf
name: cdn_refresh
org: scf
app: scfApp
stage: dev

inputs:
  name: cos_cdn_PurgeUrlsCache
  src: ./src
  runtime: Python2.7
  region: ap-shanghai  #需要替换的字段
  handler: index.main_handler
  timeout: 20
  role: SCF_QcsRole  #需要确认是否有授权CDN的接口操作权限
  environment:
    variables:
      #需要替换的字段
      url_cdn: #'https://serverless-demo-1256608914.file.myqcloud.com'
      region: #ap-shanghai
  events:
     - cos: # cos触发器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true



