component: scf
name: ap-guangzhou_default_COS_Sync_Backup
org: app
app: COS_Sync_Backup
stage: dev
inputs:
  name: COS_Sync_Backup
  src: ./
  description: >-
    This demo will backup the COS bucket object to another bucket when you
    upload the file. 此示例使用COS作为触发器，在用户上传文件到指定bucket时，将该文件复制到另一个用于备份的bucket存储
  handler: sync_backup.main_handler
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 10
  events:
     - cos: # cos触发器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true


