component: scf
name: transcode
org: scf
app: scf_transcode
stage: dev

inputs:
  name: transcode
  src: 
    src: ./
  runtime: Nodejs10.15
  region: ap-shanghai #需要替换的字段
  handler: index.main_handler
  memorySize: 3072
  timeout: 300
  role: SCF_QcsRole   #需要授权：cos bucket文件读写，cdn预热/刷新权限
  vpcConfig: # 私有网络配置
    subnetId: 'subnet-03jndatv'  #需要替换的字段
    vpcId: 'vpc-9mp2jk1a'  #需要替换的字段
  environment:
    variables:
      #region: ap-shanghai  #需要替换的字段
      #target_bucket: serverless-demo-1256608914  #需要替换的字段
      #target_path: /transcode  #需要替换的字段
  events:
    #cos触发器，上传音视频触发SCF进行处理
    - cos:
        name: serverless-demo-1256608914.cos.ap-shanghai.myqcloud.com   #需要替换的字段
        parameters:
          bucket: serverless-demo-1256608914.cos.ap-shanghai.myqcloud.com  #需要替换的字段
          filter:
            prefix: source-video/   #可选，前缀过滤，需要替换的字段
          events: cos:ObjectCreated:*
          enable: true
    # apigw触发器，post http源文件地址
    - apigw:
        name: serverless_days_workshop_transcode
        parameters:
          protocols:
            - http
            - https
          serviceName: serverless_days_workshop_transcode
          description: serverless_days_workshop
          environment: release
          endpoints:
            - path: /transcode
              method: ANY
              enableCORS: TRUE
              serviceTimeout: 300


