component: scf
name: kafka_to_kafka_consumer
org: app
app: kafka_to_kafka_consumer
stage: dev
inputs:
  name: kafka_to_kafka_consumer
  src: ./
  description: CKAFKA data backup to another CKAFKA topic. CKAFKA数据转存到另外一个CKAFKA topic。
  handler: cls_to_kafka_consumer.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128 # 根据需要设置，默认 128M
  timeout: 300 # 建议设置为 300s，不建议设置时间太短，以免超时
  vpcConfig: # 如果连接目标 ckafka 不是走公网，需要配置 vpc 信息，vpcId 和 subnetId 要跟 ckakfa 所在的 vpc 一致
    vpcId: vpc-kdx2xxxx
    subnetId: subnet-a8x0xxxx
  environment:
    variables:
      kafka_address: 172.16.xx.xxx:9092 # 必填，目标 ckafka 地址
      kafka_topic_name: xxxx # 必填，需要转存的目标 kafka topic 名称

  events:
    - ckafka: # ckafka 触发器
        name: # 触发器名称
        parameters:
          name: ckafka-8xo1xxxx # 来源 ckafka 实例 ID
          topic: source # 来源 ckakfa 的 topic 名称
          maxMsgNum: 10000 # 最大批量消息数，最大为 10000
          offset: latest # 触发器消费消息的起始位置。支持三种配置：最新、最开始、按时间点。
          enable: true # 立即启用（默认 true 即可）
