component: scf
name: ap-guangzhou_default_Video_Transcode
org: app
app: Video_Transcode
stage: dev
inputs:
  name: Video_Transcode
  src: ./
  description: 本示例通过配置COS触发器，当你在通过上传视频文件到cos时，通过云点播提供的接口，进行视频转码，并写入目标bucket中
  handler: index.main_handler
  runtime: Nodejs8.9
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
  events:
     - cos: # cos触发器
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true
