component: scf
name: ap-guangzhou_default_cdn-save-log-into-cos
org: app
app: cdn-save-log-into-cos
stage: dev
inputs:
  name: cdn-save-log-into-cos
  src: ./
  description: >-
    Get logs by url and upload to COS by streaming.
    本示例介绍如何把CDN的日志拉取并存储到对象存储，一共需要创建2个函数，任务分发函数和存储函数，通过任务分发函数调用存储函数完成日志存储，该函数为日志存储函数
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 300
