component: scf
name: cdn_edgepack
org: scf
app: scfApp
stage: dev

inputs:
  name: cos_cdn_CreateEdgePackTask
  src: ./src
  runtime: Python2.7
  region: ap-shanghai  
  handler: index.main_handler
  timeout: 20
  role: SCF_QcsRole  #需要确认是否有授权CDN的接口操作权限
  environment:
    variables:
  events:
     - cos: 
        name: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
        parameters:
          bucket: # input cosname.cos.region.myqcloud.com  //e.g. xxx.cos.ap-chengdu.myqcloud.com
          filter:
            prefix: 
            suffix: 
          events: cos:ObjectCreated:*
          enable: true



