component: scf
name: ap-guangzhou_default_cdn-dispatch-log-jobs
org: app
app: cdn-dispatch-log-jobs
stage: dev
inputs:
  name: cdn-dispatch-log-jobs
  src: ./
  description: >-
    get CDN logs by url and upload to COS. this is control function.
    本示例介绍如何把CDN的日志拉取并存储到对象存储，一共需要创建2个函数，任务分发函数和存储函数，通过任务分发函数调用“下载URL文件并存储到COS”函数完成日志存储，该函数为任务分发函数
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 300
