component: scf
name: ap-guangzhou_default_mongodb_basic_demo
org: app
app: mongodb_basic_demo
stage: dev
inputs:
  name: mongodb_basic_demo
  src: ./
  description: mongodb_basic_demo. 本示例演示基于API网关提供博客内的文章查询和文章内容，您可以扩展函数来实现 Web 后端服务
  handler: index.main_handler
  runtime: Python2.7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 3
