component: scf
name: ap-guangzhou_default_SCFonedrive
org: app
app: SCFonedrive
stage: dev
inputs:
  name: SCFonedrive
  src: ./
  description: This application is a list of your onedrive. 获取onedrive信息并结合API网关展示
  handler: index.main_handler
  runtime: Php7
  namespace: default
  region: ap-guangzhou
  memorySize: 128
  timeout: 30
  events:
     - apigw: # api网关触发器
        name: serverless
        serviceId: # input API gateway serviceId
        parameters:
          protocols:
            - http
          description: the serverless service
          environment: release
          endpoints:
            - path: /
              method: GET
              function:
                isIntegratedResponse: TRUE
