component: scf
name: COS_SyncData_SameRegion
org: scf
app: scfApp
stage: test

inputs:
  name: COS_SyncData_SameRegion
  src: 
    src: ./src
  runtime: Python3.6
  region: ap-beijing  #需要替换的字段
  handler: index.main_handler
  memorySize: 128
  timeout: 10
  role: SCF_QcsRole  #需要确认是否有授权cos的copy接口操作权限
  environment:
    variables:  #环境变量
      target_bucket: #'function-scf-1256608914'  #需要替换的字段 
      source_bucket: #'ffmpeg-1256608914'  #需要替换的字段
      region: #ap-beijing  #需要替换的字段
      
  events:
    #cos触发器配置
    - cos:
        name: ffmpeg-1256608914.cos.ap-beijing.myqcloud.com   #需要替换的字段
        parameters:
          bucket: ffmpeg-1256608914.cos.ap-beijing.myqcloud.com   #需要替换的字段
          filter:
            prefix: copy/   #需要替换的字段，可选，配置前缀过滤
          events: cos:ObjectCreated:*  
          enable: true


